"""
Agent 5: Report Generator

Assembles everything gathered by Agents 1-4 into a structured
investigation report, in both Markdown (human-readable, suitable
for a GitHub issue body) and JSON (machine-readable, suitable for
the eval harness and any downstream tooling) formats.

No LLM call needed here -- by this point all the actual content has
already been generated by earlier agents; this agent's job is pure
formatting/assembly, which keeps report structure consistent and
fast (no extra API call, no risk of the LLM paraphrasing earlier
findings inaccurately).
"""

from app.models.state import InvestigationReport, InvestigationState


def run_report_generator(state: InvestigationState) -> InvestigationState:
    """
    Entry point for Agent 5. Reads everything in state and writes
    state.report (both markdown and json_summary).
    """
    run_info = state.run_info
    classification = state.classification
    repo_finding = state.repo_finding
    fix = state.fix_recommendation

    category = classification.category.value if classification else "Unknown"
    confidence = classification.confidence if classification else 0.0
    root_cause = classification.root_cause_explanation if classification else "N/A"
    log_excerpt = classification.relevant_log_excerpt if classification else "N/A"

    likely_files = repo_finding.likely_files if repo_finding else []
    evidence = repo_finding.supporting_evidence if repo_finding else "N/A"

    suggested_fix = fix.suggested_fix if fix else "N/A"
    fix_confidence = fix.confidence if fix else 0.0

    files_list_md = "\n".join(f"- `{f}`" for f in likely_files) or "_None identified_"

    markdown = f"""## CI/CD Failure Investigation Report

**Workflow:** {run_info.workflow_name}
**Branch:** `{run_info.branch}`
**Commit:** `{run_info.commit_sha[:7]}` - {run_info.commit_message.splitlines()[0]}
**Run:** [{run_info.run_id}]({run_info.html_url})
**Detected tech stack:** {state.detected_tech_stack}

### Classification
**Category:** {category}
**Confidence:** {confidence:.2f}

### Root Cause
{root_cause}

**Relevant log excerpt:**
```
{log_excerpt}
```

### Likely Responsible File(s)
{files_list_md}

**Supporting evidence:** {evidence}

### Suggested Fix
{suggested_fix}

**Fix confidence:** {fix_confidence:.2f}

---
*Generated automatically by cicd-autopsy.*
"""

    json_summary = {
        "run_id": run_info.run_id,
        "repo": f"{run_info.repo_owner}/{run_info.repo_name}",
        "branch": run_info.branch,
        "commit_sha": run_info.commit_sha,
        "tech_stack": state.detected_tech_stack,
        "category": category,
        "classification_confidence": confidence,
        "root_cause_explanation": root_cause,
        "likely_files": likely_files,
        "suggested_fix": suggested_fix,
        "fix_confidence": fix_confidence,
        "errors": state.errors,
    }

    state.report = InvestigationReport(markdown=markdown, json_summary=json_summary)
    return state
